apiVersion: batch/v1beta1
kind: CronJob
metadata:
   name: tesing-for-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          -  name: neo4j-server
             image: neo4j:latest
             imagePullPolicy: Always
             command: ["echo", "SUCCESS"]
          restartPolicy: Never
      # backoffLimit: 4
