apiVersion: v1
kind: Pod
metadata:
   name: tesing-for-image-pull
spec:
   containers:
   -  name: neo4j-server
      image: neo4j:latest
      imagePullPolicy: Always
      command: ["echo", "SUCCESS"]
