kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    # targetPort: 9376
  # clusterIP: 10.0.171.239
  # loadBalancerIP: 78.11.24.19
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 146.148.47.155
